export const LOGIN = 'LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const BOOTSTRAP_ASYNC_PENDING = 'BOOTSTRAP_ASYNC_PENDING';
export const BOOTSTRAP_ASYNC_FULFILLED = 'BOOTSTRAP_ASYNC_FULFILLED';
export const BOOTSTRAP_ASYNC_REJECTED = 'BOOTSTRAP_ASYNC_REJECTED';

export const REGISTER = 'REGISTER';
export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_FULFILLED = 'REGISTER_FULFILLED';
export const REGISTER_REJECTED = 'REGISTER_REJECTED';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_PENDING = 'LOGOUT_PENDING';
export const LOGOUT_FULFILLED = 'LOGOUT_FULFILLED';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';

export const GET_CARTS = 'GET_CARTS';
export const GET_CARTS_PENDING = 'GET_CARTS_PENDING';
export const GET_CARTS_FULFILLED = 'GET_CARTS_FULFILLED';
export const GET_CARTS_REJECTED = 'GET_CARTS_REJECTED';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_PENDING = 'ADD_TO_CART_PENDING';
export const ADD_TO_CART_FULFILLED = 'ADD_TO_CART_FULFILLED';
export const ADD_TO_CART_REJECTED = 'ADD_TO_CART_REJECTED';

export const ADDED_TO_CART = 'ADDED_TO_CART';
export const CART_DELETED = 'CART_DELETED';

export const DELETE_CART = 'DELETE_CART';
export const DELETE_CART_PENDING = 'DELETE_CART_PENDING';
export const DELETE_CART_FULFILLED = 'DELETE_CART_FULFILLED';
export const DELETE_CART_REJECTED = 'DELETE_CART_REJECTED';

export const ADD_QUANTITY = 'ADD_QUANTITY';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const HIDE_MODAL = 'FORCE_HIDE';

export const GET_CHECKOUTS = 'GET_CHECKOUTS';
export const ADD_COURIER = 'ADD_COURIER';

export const GET_BOOKS = 'GET_BOOKS';
export const GET_BOOKS_PENDING = 'GET_BOOKS_PENDING';
export const GET_BOOKS_FULFILLED = 'GET_BOOKS_FULFILLED';
export const GET_BOOKS_REJECTED = 'GET_BOOKS_REJECTED';

export const GET_BOOK = 'GET_BOOK';
export const GET_BOOK_PENDING = 'GET_BOOK_PENDING';
export const GET_BOOK_FULFILLED = 'GET_BOOK_FULFILLED';
export const GET_BOOK_REJECTED = 'GET_BOOK_REJECTED';

export const GET_MORE_BOOKS = 'GET_MORE_BOOKS';
export const GET_MORE_BOOKS_PENDING = 'GET_MORE_BOOKS_PENDING';
export const GET_MORE_BOOKS_FULFILLED = 'GET_MORE_BOOKS_FULFILLED';
export const GET_MORE_BOOKS_REJECTED = 'GET_MORE_BOOKS_REJECTED';

export const GET_GENRES = 'GET_GENRES';
export const GET_GENRES_PENDING = 'GET_GENRES_PENDING';
export const GET_GENRES_FULFILLED = 'GET_GENRES_FULFILLED';
export const GET_GENRES_REJECTED = 'GET_GENRES_REJECTED';
